# The 'version' line has been removed
services:
  # --- 1. PostgreSQL Database Service ---
  postgres-db:
    image: postgres:15
    container_name: treeview_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # --- ADD THIS HEALTHCHECK ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # --- END OF HEALTHCHECK ---

  # --- 2. Backend Server Service ---
  server:
    build:
      context: ./server
    container_name: treeview_server
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}"
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    # --- UPDATE depends_on TO USE THE HEALTHCHECK ---
    depends_on:
      postgres-db:
        condition: service_healthy # Wait for the healthcheck to pass
    # --- END OF UPDATE ---

  # --- 3. Frontend Client Service ---
  client:
    build:
      context: ./client
    container_name: treeview_client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  pgdata: